#' Monthly resolution of discharge value projections
#'
#' @description Function allows to compare seasonality of monthly averaged minimum dischargeva lues for 3 rivers and one scenario.
#'
#' @param rivernames vector; contains rivernames as they are listed in the dataset (mod_data)
#' @param sel_names vector; contains rivernames as they appear in the plot
#' @param mod_data list in a tidy order, as it is generated by \link[lfanalyse]{datascen} function. List combines all rivers and projected values.
#' @param scenario charcter, One out of 3 representative RCP Scnearios (2p6, 6p0, 8p5).
#' @param NF numerical; vector containing all the years that account for the near future. The function itself operates with hydrological years.
#' @param FF numerical; vector containing all the years that account for the far future. The function itself operates with hydrological years.
#' @param P numerical; vector containing all the years that account for the past. The function itself operates with hydrological years.
#'
#' @return seasonal plot with monthly resolutio
#' @import ggplot2
#' @export
#'
#' @examples \dontrun{pl=seasonalproj(rivernames, sel_names , mod_data)}
seasonalproj=function(rivernames, sel_names, mod_data, NF,FF, scenario){


  river1= mod_data[[which(names(mod_data)==rivernames[1])]]

  hist1=river1 %>% filter(scenario=="hist")
  scen1=river1 %>% filter(scenario==scen)

  river1=rbind(hist1,scen1)
  river1$name=rep(sel_names[1], nrow( river1))

  colnames(river1)=c("date", "Value", "scenario", "model" ,"name")







  river2= mod_data[[which(names(mod_data)==rivernames[2])]]
  hist2=river2 %>% filter(scenario=="hist")
  scen2=river2 %>% filter(scenario==scen)
  river2=rbind(hist2,scen2)

  river2$name=rep(sel_names[2], nrow( river2))

  colnames(river2)=c("date", "Value", "scenario", "model" ,"name")



  river3= mod_data[[which(names(mod_data)==rivernames[3])]]
  hist3=river3 %>% filter(scenario=="hist")
  scen3=river3 %>% filter(scenario==scen)
  river3=rbind(hist3,scen3)

  river3$name=rep(sel_names[3], nrow( river3))

  colnames(river3)=c("date", "Value", "scenario", "model" ,"name")


  riverdata=rbind(river1, river2, river3)



  datum=format(riverdata$date, "%m")
  Nov=sub("11", 1, datum)
  Dez=sub("12", 2, Nov)
  Dez
  Jan=sub("01",3, Dez)
  Jan
  Feb=sub("02", 4, Jan)
  Mar=sub("03", 5, Feb)
  Apr=sub("04", 6, Mar)
  May=sub("05", 7, Apr)
  Jun=sub("06", 8, May)
  Jul=sub("07", 9, Jun)

  Aug=sub("08", 9.2, Jul)
  Sep=sub("09",9.3, Aug)
  Oct=sub("10",9.4, Sep)
  Oct=sub("9.2", 10, Oct)
  Oct=sub("9.3", 11, Oct)
  Oct=sub("9.4", 12, Oct)

  Year=as.numeric(Oct)

  riverdata$month=Year




  years=as.numeric(format(riverdata$date, "%Y"))
  timespan=rep(0,length(years))
  for (i in 1:length(years)){
    if(is.element(years[i],P)==T){
      timespan[i]="1.P"
    }else if(is.element(years[i],NF)==T)
      timespan[i]="2.NF"
    else if(is.element(years[i],FF)==T)
      timespan[i]="3.FF"
    else{timespan[i]="NotElement"}

  }
  riverdata$timespan=timespan
  #eliminating data that is not within requested timespans
  riverdata=riverdata[-which(timespan=="NotElement"),]

  #Integrate Low Flow Value

  year_month=format(riverdata$date,"%Y-%m")
  year=format(riverdata$date,"%Y")

  ym_unique=unique(year_month)
  m_minvals=rep(0,length(ym_unique))
  date=rep(0,length(ym_unique))
  scenario=rep(0,length(ym_unique))
  name=rep(0,length(ym_unique))
  month=rep(0,length(ym_unique))
  timespan=rep(0,length(ym_unique))

  riverdata$ym=year_month


  #First:Past
  Mainh=riverdata %>% filter(  name=="Main",timespan=="1.P")
  minvals=rep(0,nrow(Mainh))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],Mainh$ym)){
      minval=Mainh$Value[which(Mainh$ym==ym_unique[i])]

      minvals[which(Mainh$ym==ym_unique[i])]=min(minval)
    }
  }
  Mainh$minval=minvals



  Moselh=riverdata %>% filter(  name=="Mosel",timespan=="1.P")
  minvals=rep(0,nrow(Moselh))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],Moselh$ym)){
      minval=Moselh$Value[which(Moselh$ym==ym_unique[i])]

      minvals[which(Moselh$ym==ym_unique[i])]=min(minval)
    }
  }
  Moselh$minval=minvals



  Neckarh=riverdata %>% filter(  name=="Neckar",timespan=="1.P")
  minvals=rep(0,nrow(Neckarh))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],Neckarh$ym)){
      minval=Neckarh$Value[which(Neckarh$ym==ym_unique[i])]

      minvals[which(Neckarh$ym==ym_unique[i])]=min(minval)
    }
  }
  Neckarh$minval=minvals


  #Second NF
  MainNF=riverdata %>% filter(  name=="Main",timespan=="2.NF")
  minvals=rep(0,nrow(MainNF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],MainNF$ym)){
      minval=MainNF$Value[which(MainNF$ym==ym_unique[i])]

      minvals[which(MainNF$ym==ym_unique[i])]=min(minval)
    }
  }
  MainNF$minval=minvals



  MoselNF=riverdata %>% filter(  name=="Mosel",timespan=="2.NF")
  minvals=rep(0,nrow(MoselNF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],MoselNF$ym)){
      minval=MoselNF$Value[which(MoselNF$ym==ym_unique[i])]

      minvals[which(MoselNF$ym==ym_unique[i])]=min(minval)
    }
  }
  MoselNF$minval=minvals


  NeckarNF=riverdata %>% filter(  name=="Neckar",timespan=="2.NF")
  minvals=rep(0,nrow(NeckarNF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],NeckarNF$ym)){
      minval=NeckarNF$Value[which(NeckarNF$ym==ym_unique[i])]

      minvals[which(NeckarNF$ym==ym_unique[i])]=min(minval)
    }
  }
  NeckarNF$minval=minvals


  # 3rd FF


  MainFF=riverdata %>% filter(  name=="Main",timespan=="3.FF")
  minvals=rep(0,nrow(MainFF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],MainFF$ym)){
      minval=MainFF$Value[which(MainFF$ym==ym_unique[i])]

      minvals[which(MainFF$ym==ym_unique[i])]=min(minval)
    }
  }
  MainFF$minval=minvals



  MoselFF=riverdata %>% filter(  name=="Mosel",timespan=="3.FF")
  minvals=rep(0,nrow(MoselFF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],MoselFF$ym)){
      minval=MoselFF$Value[which(MoselFF$ym==ym_unique[i])]

      minvals[which(MoselFF$ym==ym_unique[i])]=min(minval)
    }
  }
  MoselFF$minval=minvals


  NeckarFF=riverdata %>% filter(  name=="Neckar",timespan=="3.FF")
  minvals=rep(0,nrow(NeckarFF))
  for(i in 1:length(ym_unique)){
    if(is.element(ym_unique[i],NeckarFF$ym)){
      minval=NeckarFF$Value[which(NeckarFF$ym==ym_unique[i])]

      minvals[which(NeckarFF$ym==ym_unique[i])]=min(minval)
    }
  }
  NeckarFF$minval=minvals





  Minvals=rbind(Mainh, Moselh, Neckarh,MainNF, MoselNF, NeckarNF, MainFF, MoselFF, NeckarFF)
  View(Minvals)
  # plot the resultsView
  Minvals$month=as.character(Minvals$month)

  View(Minvals)
  plot=ggplot(data=Minvals, aes(x=month, y=minval))+geom_boxplot(aes(fill=timespan))+scale_x_discrete(limits = c("Jan"="1","2","3","4", "5", "6","7","8","9","10","11","12"), labels=c("1"="Nov","2"="Dec","3"="Jan","4"="Feb", "5"="Mär", "6"="Apr","7"="Mai","8"="Jun","9"="Jul","10"="Aug","11"="Sep","12"="Okt"))+facet_wrap( ~ name, ncol=1, scales="free")+
    labs(title="Mittlere Abflussminima in monatlicher Auflösung", subtitle="Near- und Far Future Zeiträume für RCP6p0", fill="Zeitspanne:")+ scale_fill_manual(values=c("grey85", "gold1", "gold3"))+ theme(legend.position="bottom")+ylab( expression(paste("Abfluss [" , m^{3},"/s]")))+xlab("Monat")
  plot

  return( plot)
}
