#' Monthly resolution of discharge value projections
#'
#' @description Function allows to compare seasonality of projected discharge values for 3 rivers.
#'
#' @param rivernames vector; contains rivernames as they are listed in the dataset (mod_data)
#' @param sel_names vector; contains rivernames as they appear in the plot
#' @param mod_data list in a tidy order, as it is generated by \link[lfanalyse]{datascen} function. List combines all rivers and projected values.
#'
#' @return
#' @import ggplot2
#' @import ggpubr
#' @export
#'
#' @examples \dontrun{pl=seasonalproj(rivernames, sel_names , mod_data)}
seasonalproj=function(rivernames, sel_names, mod_data){





  river1= mod_data[[which(names(mod_data)==rivernames[1])]]
  river1$scenario[which(river1$scenario=="hist")]="1.hist"
  river1$name=rep(sel_names[1], nrow( river1))

  colnames(river1)=c("date", "Value", "scenario", "model" ,"name")


  river2= mod_data[[which(names(mod_data)==rivernames[2])]]
  river2$scenario[which(river2$scenario=="hist")]="1.hist"
  river2$name=rep(sel_names[2], nrow( river2))

  colnames(river2)=c("date", "Value", "scenario", "model" ,"name")



  river3= mod_data[[which(names(mod_data)==rivernames[3])]]
  river3$scenario[which(river3$scenario=="hist")]="1.hist"
  river3$name=rep(sel_names[3], nrow( river3))

  colnames(river3)=c("date", "Value", "scenario", "model" ,"name")



  riverdata=rbind(river1, river2, river3)

  datum=format(riverdata$date, "%m")
  Nov=sub("11", 1, datum)
  Dec=sub("12", 2, Nov)
  Dec
  Jan=sub("01",3, Dec)
  Jan
  Feb=sub("02", 4, Jan)
  Mar=sub("03", 5, Feb)
  Apr=sub("04", 6, Mar)
  May=sub("05", 7, Apr)
  Jun=sub("06", 8, May)
  Jul=sub("07", 9, Jun)

  Aug=sub("08", 9.2, Jul)
  Sep=sub("09",9.3, Aug)
  Oct=sub("10",9.4, Sep)
  Oct=sub("9.2", 10, Oct)
  Oct=sub("9.3", 11, Oct)
  Oct=sub("9.4", 12, Oct)

  Year=as.numeric(Oct)

  riverdata$month=Year




  #ggplot(data=riverdata, aes(x=hydroyear, y=Value, fill=scenario))+geom_bar(stat="identity",position=position_dodge())+  scale_fill_brewer(palette="YlGnBu")+scale_x_discrete(limit = c("Nov", "Dec", "Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Oct"))+
  #   labs(title = "Abflusswerte in monatlicher Auflösung", x = "Monat", y = expression(Abfluss~ m^3/s ))+facet_wrap( ~ name, ncol=1)+
  #  stat_summary(aes(color =scenario),
  #    fun.data = "mean_sdl", fun.args = list(mult=1),
  #    geom = "pointrange", color = "black", size=0.04
  #  )


  #ggbarplot(riverdata, x="hydroyear", y="Value",  add  = c("mean_sd"), fill="scenario", palette = c("rickandmorty"), width=0.5,
  #  position = position_dodge(0.8))+  labs(title = "Abflusswerte in monatlicher Auflösung", x = "Monat", y = expression(Abfluss~ m^3/s ))+facet_wrap( ~ name, ncol=1)

  #ggline(riverdata, x="hydroyear", y="Value",  add  = c("mean_sd"), error.plot = "pointrange",color = "scenario", palette = c("rickandmorty"))+facet_wrap( ~ name, ncol=1)+ labs(title = "Abflusswerte in monatlicher Auflösung", x = "Monat", y = expression(Abfluss~ m^3/s ))+facet_wrap( ~ name, ncol=1)

  #e <- ggplot(riverdata, aes(x = hydroyear, y = Value))+ geom_dotplot(
  # binaxis = "y", stackdir = "center",
  #  fill = "lightgray"
  #) +
  #  stat_summary(
  #    fun.data = "mean_sdl", fun.args = list(mult=1),
  #    geom = "pointrange", color = "red", geom_dotplot(
  #  binaxis = "y", stackdir = "center",
  #  fill = "lightgray"
  #  ) +
  #  stat_summary(
  #    fun.data = "mean_sdl", fun.args = list(mult=1),
  #    geom = "pointrange", color = "red", size=0.4
  #    )
  # )
  plot=ggplot(data=riverdata, aes(x=month, y=Value, fill=scenario))+

    stat_summary(fun = "mean", geom = "bar",
                 alpha = .7, position = position_dodge(0.75)) +
    stat_summary(fun = "mean", geom = "point",
                 position = position_dodge(0.75),
                 size = 0.01) +
    stat_summary(fun.data = "mean_cl_normal",
                 geom = "errorbar",
                 position = position_dodge(0.75),
                 width = .5) +  scale_fill_brewer(palette="YlGnBu")+scale_x_discrete(limit = c("Nov", "Dec", "Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt"))+
    labs(title = "Abflusswerte in monatlicher Auflösung", x = "Monat", y = expression(Abfluss~ m^3/s ))+facet_wrap( ~ name, ncol=1)

  return(plot)

}
